# OpenAI Provider Definition
id = "openai"
name = "OpenAI"
base_url = "https://api.openai.com/v1"
doc = "https://platform.openai.com/docs"

env = ["OPENAI_API_KEY"]

exclude_models = [
  "o1-preview",
  "o1-mini",
  "o1-pro",
  "o3-deep-research",
  "o4-mini-deep-research",
  "codex-mini-latest"
]
