id = "text-embedding-3-small"
name = "Text Embedding 3 Small"
provider_model_id = "text-embedding-3-small"
knowledge = "2024-01"
release_date = "2024-01-25"
last_updated = "2024-01-25"

[limits]
context = 8191

[cost]
input = 0.00002

[modalities]
input = ["text"]
output = ["embedding"]

[capabilities.embeddings]
min_dimensions = 1
max_dimensions = 1536
default_dimensions = 1536

[extra]
type = "embedding"
attachment = false
open_weights = false
reasoning = false
temperature = false
tool_call = false
