id = "text-embedding-3-small"

[capabilities.embeddings]
min_dimensions = 1
max_dimensions = 1536
default_dimensions = 1536

[modalities]
input = ["text"]
output = ["text", "embedding"]

[extra]
type = "embedding"
