id = "text-embedding-3-large"

[capabilities.embeddings]
min_dimensions = 1
max_dimensions = 3072
default_dimensions = 3072

[modalities]
input = ["text"]
output = ["text", "embedding"]

[extra]
type = "embedding"
